# Generated by Django 3.2.11 on 2022-04-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('profile', models.CharField(choices=[('I', 'Investor'), ('S', 'Student')], max_length=1)),
                ('amount_invest', models.IntegerField()),
                ('investment_duration', models.IntegerField()),
                ('geolocation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('profile', models.CharField(choices=[('I', 'Investor'), ('S', 'Student')], max_length=1)),
                ('desire_amount', models.IntegerField()),
                ('loan_period', models.IntegerField()),
                ('cumulative_income', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('school_rank', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('borrowing_date', models.DateField()),
                ('repayment_date', models.DateField()),
                ('loan_duration', models.IntegerField()),
                ('loan_state', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], max_length=1)),
                ('rate', models.IntegerField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invest', models.IntegerField()),
                ('investment_date', models.DateField()),
                ('investment_duration', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.investor')),
            ],
        ),
    ]
