# Generated by Django 3.2.11 on 2022-05-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('profile', models.CharField(choices=[('INVESTOR', 'Investor'), ('STUDENT', 'Student'), ('ADMIN', 'Administrateur')], max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.person')),
                ('amount_invest', models.IntegerField()),
                ('investment_duration', models.IntegerField()),
                ('geolocation', models.CharField(max_length=100)),
            ],
            bases=('home.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.person')),
                ('desire_amount', models.IntegerField()),
                ('loan_period', models.IntegerField()),
                ('cumulative_income', models.IntegerField()),
                ('school', models.CharField(max_length=100, null=True)),
                ('school_rank', models.IntegerField()),
                ('score_loan', models.IntegerField(default=10)),
            ],
            bases=('home.person',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.investor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('borrowing_date', models.DateField(auto_now=True)),
                ('repayment_date', models.DateField(null=True)),
                ('loan_duration', models.IntegerField()),
                ('percentage_invest', models.IntegerField(null=True)),
                ('loan_state', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='P', max_length=1)),
                ('rate', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_invest', models.IntegerField()),
                ('investment_date', models.DateField(auto_now=True)),
                ('investment_duration', models.IntegerField()),
                ('rendement', models.IntegerField()),
                ('montant_attendu', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.loan')),
                ('investor', models.ManyToManyField(to='home.Investor')),
            ],
        ),
    ]
