# Generated by Django 3.2.11 on 2022-04-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ethnicity',
        ),
        migrations.AddField(
            model_name='investor',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='score_loan',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.investor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
