# Generated by Django 3.2.11 on 2022-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220428_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='profile',
            field=models.CharField(choices=[('INVESTOR', 'Investor'), ('STUDENT', 'Student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.CharField(choices=[('INVESTOR', 'Investor'), ('STUDENT', 'Student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
