# Generated by Django 3.2.11 on 2022-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_person_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='percentage_invest',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
