# Generated by Django 3.2.11 on 2022-05-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_loan_percentage_invest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='user',
        ),
    ]
