# Generated by Django 3.2.11 on 2022-04-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220428_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrowing_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_state',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_date',
            field=models.DateField(null=True),
        ),
    ]
